// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.4

package types

type AnchorJson struct {
	Uid     string `json:"uid"`
	RoomNum string `json:"roomNum"`
	Detail  string `json:"detail"`
	Notice  string `json:"notice"`
	Live    bool   `json:"live"`
}

type CacheRefreshReq struct {
	Family string `json:"family"`
}

type CacheRefreshResp struct {
	Ok      bool   `json:"ok"`
	Message string `json:"message"`
}

type CacheStatsResp struct {
	Hits     int64            `json:"hits"`
	Misses   int64            `json:"misses"`
	Keys     int64            `json:"keys"`
	Families []FamilyStatJson `json:"families"`
}

type CateListResp struct {
	CateNames []string `json:"cateNames"`
}

type CateReq struct {
	CateName string `form:"cateName"`
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=20"`
}

type CommentatorDetailResp struct {
	Commentator CommentatorJson `json:"commentator"`
}

type CommentatorJson struct {
	Uid        string     `json:"uid"`
	NickName   string     `json:"nickName"`
	Icon       string     `json:"icon"`
	CutOutIcon string     `json:"cutOutIcon"`
	Intro      string     `json:"intro"`
	Fans       int64      `json:"fans"`
	Follow     int64      `json:"follow"`
	Hot        int64      `json:"hot"`
	Anchor     AnchorJson `json:"anchor"`
}

type CommentatorListResp struct {
	List  []CommentatorJson `json:"list"`
	Total int64             `json:"total"`
}

type DateReq struct {
	Date     string `form:"date,optional"`
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=20"`
}

type FamilyStatJson struct {
	Family string `json:"family"`
	Keys   int64  `json:"keys"`
	Hits   int64  `json:"hits"`
	Misses int64  `json:"misses"`
}

type HotAnchorResp struct {
	List []CommentatorJson `json:"list"`
}

type IdReq struct {
	Id string `form:"id"`
}

type LiveListResp struct {
	List  []LiveRoomJson `json:"list"`
	Total int64          `json:"total"`
}

type LiveRoomJson struct {
	RoomNum  string          `json:"roomNum"`
	Title    string          `json:"title"`
	Cover    string          `json:"cover"`
	Anchor   CommentatorJson `json:"anchor"`
	ViewNum  int64           `json:"viewNum"`
	LiveType string          `json:"liveType"`
	CateName string          `json:"cateName"`
}

type LiveTypeJson struct {
	Code string `json:"code"`
	Name string `json:"name"`
	Icon string `json:"icon"`
}

type LiveTypeListResp struct {
	List []LiveTypeJson `json:"list"`
}

type LoginReq struct {
	Phone       string `json:"phone"`
	CountryCode string `json:"countryCode"`
	Password    string `json:"password"`
}

type MatchDetailResp struct {
	Match MatchItemJson `json:"match"`
}

type MatchItemJson struct {
	ScheduleId        string            `json:"scheduleId"`
	SubCateName       string            `json:"subCateName"`
	CateName          string            `json:"cateName"`
	MatchTime         string            `json:"matchTime"`
	HostName          string            `json:"hostName"`
	HostIcon          string            `json:"hostIcon"`
	GuestName         string            `json:"guestName"`
	GuestIcon         string            `json:"guestIcon"`
	Venue             string            `json:"venue"`
	Status            string            `json:"status"`
	ReservationStatus int32             `json:"reservationStatus"`
	Anchors           []CommentatorJson `json:"anchors"`
}

type MatchListResp struct {
	List  []MatchItemJson `json:"list"`
	Total int64           `json:"total"`
	Date  string          `json:"date"`
}

type MatchRecommendResp struct {
	List []MatchItemJson `json:"list"`
}

type PageReq struct {
	Page     int32 `form:"page,default=1"`
	PageSize int32 `form:"pageSize,default=20"`
}

type RefreshReq struct {
	RefreshToken string `json:"refreshToken"`
}

type RegisterReq struct {
	LoginName   string `json:"loginName"`
	Phone       string `json:"phone"`
	CountryCode string `json:"countryCode"`
	Password    string `json:"password"`
	SmsCode     string `json:"smsCode"`
}

type RoomDetailJson struct {
	RoomNum    string          `json:"roomNum"`
	Title      string          `json:"title"`
	Cover      string          `json:"cover"`
	Live       bool            `json:"live"`
	ViewNum    int64           `json:"viewNum"`
	LiveType   string          `json:"liveType"`
	Anchor     CommentatorJson `json:"anchor"`
	StreamUrls []string        `json:"streamUrls"`
	Notice     string          `json:"notice"`
	Tags       []string        `json:"tags"`
}

type RoomDetailResp struct {
	Room RoomDetailJson `json:"room"`
}

type RoomNumReq struct {
	RoomNum string `form:"roomNum"`
}

type RoomRankItemJson struct {
	Uid      string `json:"uid"`
	NickName string `json:"nickName"`
	Icon     string `json:"icon"`
	Score    int64  `json:"score"`
	Rank     int32  `json:"rank"`
}

type RoomRankResp struct {
	List []RoomRankItemJson `json:"list"`
}

type RoomScheduleResp struct {
	List []MatchItemJson `json:"list"`
}

type TokenResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresAt    int64  `json:"expiresAt"`
}

type UserProfileResp struct {
	Uid         string `json:"uid"`
	LoginName   string `json:"loginName"`
	NickName    string `json:"nickName"`
	Phone       string `json:"phone"`
	CountryCode string `json:"countryCode"`
	Grow        int64  `json:"grow"`
	Score       int64  `json:"score"`
	Level       int32  `json:"level"`
	Avatar      string `json:"avatar"`
	IsUser      int32  `json:"isUser"`
	CreatedAt   int64  `json:"createdAt"`
}
