// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.4

package handler

import (
	"net/http"

	admin "apipro/cmd/api/internal/handler/admin"
	auth "apipro/cmd/api/internal/handler/auth"
	commentator "apipro/cmd/api/internal/handler/commentator"
	live "apipro/cmd/api/internal/handler/live"
	match "apipro/cmd/api/internal/handler/match"
	room "apipro/cmd/api/internal/handler/room"
	user "apipro/cmd/api/internal/handler/user"
	"apipro/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: admin.RefreshHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/stats",
				Handler: admin.StatsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin/cache"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/guest",
				Handler: auth.GuestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: auth.RefreshHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: commentator.DetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: commentator.ListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/commentator"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/hot",
				Handler: live.HotAnchorHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: live.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/types",
				Handler: live.TypesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/live"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/cate",
				Handler: match.ListByCateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/cates",
				Handler: match.CateListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: match.DetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: match.ListByDateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/recommend",
				Handler: match.RecommendHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/match"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: room.DetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/rank",
				Handler: room.RankHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/schedule",
				Handler: room.ScheduleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/room"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/profile",
				Handler: user.ProfileHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/user"),
	)
}
