// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.4
// Source: apipro.proto

package apiproClient

import (
	"context"

	"apipro/desc/proto/gen/apipro"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Anchor                = apipro.Anchor
	CacheRefreshReq       = apipro.CacheRefreshReq
	CacheRefreshResp      = apipro.CacheRefreshResp
	CacheStatsResp        = apipro.CacheStatsResp
	CateListResp          = apipro.CateListResp
	CateReq               = apipro.CateReq
	Commentator           = apipro.Commentator
	CommentatorDetailResp = apipro.CommentatorDetailResp
	CommentatorListResp   = apipro.CommentatorListResp
	DateReq               = apipro.DateReq
	Empty                 = apipro.Empty
	FamilyStat            = apipro.FamilyStat
	GuestReq              = apipro.GuestReq
	HotAnchorResp         = apipro.HotAnchorResp
	IdReq                 = apipro.IdReq
	LiveListResp          = apipro.LiveListResp
	LiveRoom              = apipro.LiveRoom
	LiveType              = apipro.LiveType
	LiveTypeListResp      = apipro.LiveTypeListResp
	LoginReq              = apipro.LoginReq
	MatchDetailResp       = apipro.MatchDetailResp
	MatchItem             = apipro.MatchItem
	MatchListResp         = apipro.MatchListResp
	MatchRecommendResp    = apipro.MatchRecommendResp
	PageReq               = apipro.PageReq
	RefreshReq            = apipro.RefreshReq
	RegisterReq           = apipro.RegisterReq
	RoomDetail            = apipro.RoomDetail
	RoomDetailResp        = apipro.RoomDetailResp
	RoomNumReq            = apipro.RoomNumReq
	RoomRankItem          = apipro.RoomRankItem
	RoomRankResp          = apipro.RoomRankResp
	RoomScheduleResp      = apipro.RoomScheduleResp
	TokenResp             = apipro.TokenResp
	UidReq                = apipro.UidReq
	UserInfo              = apipro.UserInfo
	UserProfileResp       = apipro.UserProfileResp

	Apipro interface {
		// auth
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*TokenResp, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*TokenResp, error)
		GuestLogin(ctx context.Context, in *GuestReq, opts ...grpc.CallOption) (*TokenResp, error)
		RefreshToken(ctx context.Context, in *RefreshReq, opts ...grpc.CallOption) (*TokenResp, error)
		GetUserProfile(ctx context.Context, in *UidReq, opts ...grpc.CallOption) (*UserProfileResp, error)
		// commentator
		CommentatorList(ctx context.Context, in *PageReq, opts ...grpc.CallOption) (*CommentatorListResp, error)
		CommentatorDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*CommentatorDetailResp, error)
		// match
		MatchListByDate(ctx context.Context, in *DateReq, opts ...grpc.CallOption) (*MatchListResp, error)
		MatchRecommend(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MatchRecommendResp, error)
		MatchDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*MatchDetailResp, error)
		MatchCateList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CateListResp, error)
		MatchListByCate(ctx context.Context, in *CateReq, opts ...grpc.CallOption) (*MatchListResp, error)
		// room
		RoomDetail(ctx context.Context, in *RoomNumReq, opts ...grpc.CallOption) (*RoomDetailResp, error)
		RoomSchedule(ctx context.Context, in *RoomNumReq, opts ...grpc.CallOption) (*RoomScheduleResp, error)
		RoomRank(ctx context.Context, in *RoomNumReq, opts ...grpc.CallOption) (*RoomRankResp, error)
		// live
		LiveList(ctx context.Context, in *PageReq, opts ...grpc.CallOption) (*LiveListResp, error)
		LiveTypeList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LiveTypeListResp, error)
		HotAnchor(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HotAnchorResp, error)
		// cache admin
		RefreshCache(ctx context.Context, in *CacheRefreshReq, opts ...grpc.CallOption) (*CacheRefreshResp, error)
		CacheStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CacheStatsResp, error)
	}

	defaultApipro struct {
		cli zrpc.Client
	}
)

func NewApipro(cli zrpc.Client) Apipro {
	return &defaultApipro{
		cli: cli,
	}
}

// auth
func (m *defaultApipro) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*TokenResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultApipro) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*TokenResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultApipro) GuestLogin(ctx context.Context, in *GuestReq, opts ...grpc.CallOption) (*TokenResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.GuestLogin(ctx, in, opts...)
}

func (m *defaultApipro) RefreshToken(ctx context.Context, in *RefreshReq, opts ...grpc.CallOption) (*TokenResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

func (m *defaultApipro) GetUserProfile(ctx context.Context, in *UidReq, opts ...grpc.CallOption) (*UserProfileResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.GetUserProfile(ctx, in, opts...)
}

// commentator
func (m *defaultApipro) CommentatorList(ctx context.Context, in *PageReq, opts ...grpc.CallOption) (*CommentatorListResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.CommentatorList(ctx, in, opts...)
}

func (m *defaultApipro) CommentatorDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*CommentatorDetailResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.CommentatorDetail(ctx, in, opts...)
}

// match
func (m *defaultApipro) MatchListByDate(ctx context.Context, in *DateReq, opts ...grpc.CallOption) (*MatchListResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.MatchListByDate(ctx, in, opts...)
}

func (m *defaultApipro) MatchRecommend(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MatchRecommendResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.MatchRecommend(ctx, in, opts...)
}

func (m *defaultApipro) MatchDetail(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*MatchDetailResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.MatchDetail(ctx, in, opts...)
}

func (m *defaultApipro) MatchCateList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CateListResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.MatchCateList(ctx, in, opts...)
}

func (m *defaultApipro) MatchListByCate(ctx context.Context, in *CateReq, opts ...grpc.CallOption) (*MatchListResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.MatchListByCate(ctx, in, opts...)
}

// room
func (m *defaultApipro) RoomDetail(ctx context.Context, in *RoomNumReq, opts ...grpc.CallOption) (*RoomDetailResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.RoomDetail(ctx, in, opts...)
}

func (m *defaultApipro) RoomSchedule(ctx context.Context, in *RoomNumReq, opts ...grpc.CallOption) (*RoomScheduleResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.RoomSchedule(ctx, in, opts...)
}

func (m *defaultApipro) RoomRank(ctx context.Context, in *RoomNumReq, opts ...grpc.CallOption) (*RoomRankResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.RoomRank(ctx, in, opts...)
}

// live
func (m *defaultApipro) LiveList(ctx context.Context, in *PageReq, opts ...grpc.CallOption) (*LiveListResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.LiveList(ctx, in, opts...)
}

func (m *defaultApipro) LiveTypeList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LiveTypeListResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.LiveTypeList(ctx, in, opts...)
}

func (m *defaultApipro) HotAnchor(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HotAnchorResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.HotAnchor(ctx, in, opts...)
}

// cache admin
func (m *defaultApipro) RefreshCache(ctx context.Context, in *CacheRefreshReq, opts ...grpc.CallOption) (*CacheRefreshResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.RefreshCache(ctx, in, opts...)
}

func (m *defaultApipro) CacheStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CacheStatsResp, error) {
	client := apipro.NewApiproClient(m.cli.Conn())
	return client.CacheStats(ctx, in, opts...)
}
