// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.4
// Source: apipro.proto

package server

import (
	"context"

	"apipro/cmd/rpc/internal/logic"
	"apipro/cmd/rpc/internal/svc"
	"apipro/desc/proto/gen/apipro"
)

type ApiproServer struct {
	svcCtx *svc.ServiceContext
	apipro.UnimplementedApiproServer
}

func NewApiproServer(svcCtx *svc.ServiceContext) *ApiproServer {
	return &ApiproServer{
		svcCtx: svcCtx,
	}
}

// auth
func (s *ApiproServer) Register(ctx context.Context, in *apipro.RegisterReq) (*apipro.TokenResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *ApiproServer) Login(ctx context.Context, in *apipro.LoginReq) (*apipro.TokenResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *ApiproServer) GuestLogin(ctx context.Context, in *apipro.GuestReq) (*apipro.TokenResp, error) {
	l := logic.NewGuestLoginLogic(ctx, s.svcCtx)
	return l.GuestLogin(in)
}

func (s *ApiproServer) RefreshToken(ctx context.Context, in *apipro.RefreshReq) (*apipro.TokenResp, error) {
	l := logic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

func (s *ApiproServer) GetUserProfile(ctx context.Context, in *apipro.UidReq) (*apipro.UserProfileResp, error) {
	l := logic.NewGetUserProfileLogic(ctx, s.svcCtx)
	return l.GetUserProfile(in)
}

// commentator
func (s *ApiproServer) CommentatorList(ctx context.Context, in *apipro.PageReq) (*apipro.CommentatorListResp, error) {
	l := logic.NewCommentatorListLogic(ctx, s.svcCtx)
	return l.CommentatorList(in)
}

func (s *ApiproServer) CommentatorDetail(ctx context.Context, in *apipro.IdReq) (*apipro.CommentatorDetailResp, error) {
	l := logic.NewCommentatorDetailLogic(ctx, s.svcCtx)
	return l.CommentatorDetail(in)
}

// match
func (s *ApiproServer) MatchListByDate(ctx context.Context, in *apipro.DateReq) (*apipro.MatchListResp, error) {
	l := logic.NewMatchListByDateLogic(ctx, s.svcCtx)
	return l.MatchListByDate(in)
}

func (s *ApiproServer) MatchRecommend(ctx context.Context, in *apipro.Empty) (*apipro.MatchRecommendResp, error) {
	l := logic.NewMatchRecommendLogic(ctx, s.svcCtx)
	return l.MatchRecommend(in)
}

func (s *ApiproServer) MatchDetail(ctx context.Context, in *apipro.IdReq) (*apipro.MatchDetailResp, error) {
	l := logic.NewMatchDetailLogic(ctx, s.svcCtx)
	return l.MatchDetail(in)
}

func (s *ApiproServer) MatchCateList(ctx context.Context, in *apipro.Empty) (*apipro.CateListResp, error) {
	l := logic.NewMatchCateListLogic(ctx, s.svcCtx)
	return l.MatchCateList(in)
}

func (s *ApiproServer) MatchListByCate(ctx context.Context, in *apipro.CateReq) (*apipro.MatchListResp, error) {
	l := logic.NewMatchListByCateLogic(ctx, s.svcCtx)
	return l.MatchListByCate(in)
}

// room
func (s *ApiproServer) RoomDetail(ctx context.Context, in *apipro.RoomNumReq) (*apipro.RoomDetailResp, error) {
	l := logic.NewRoomDetailLogic(ctx, s.svcCtx)
	return l.RoomDetail(in)
}

func (s *ApiproServer) RoomSchedule(ctx context.Context, in *apipro.RoomNumReq) (*apipro.RoomScheduleResp, error) {
	l := logic.NewRoomScheduleLogic(ctx, s.svcCtx)
	return l.RoomSchedule(in)
}

func (s *ApiproServer) RoomRank(ctx context.Context, in *apipro.RoomNumReq) (*apipro.RoomRankResp, error) {
	l := logic.NewRoomRankLogic(ctx, s.svcCtx)
	return l.RoomRank(in)
}

// live
func (s *ApiproServer) LiveList(ctx context.Context, in *apipro.PageReq) (*apipro.LiveListResp, error) {
	l := logic.NewLiveListLogic(ctx, s.svcCtx)
	return l.LiveList(in)
}

func (s *ApiproServer) LiveTypeList(ctx context.Context, in *apipro.Empty) (*apipro.LiveTypeListResp, error) {
	l := logic.NewLiveTypeListLogic(ctx, s.svcCtx)
	return l.LiveTypeList(in)
}

func (s *ApiproServer) HotAnchor(ctx context.Context, in *apipro.Empty) (*apipro.HotAnchorResp, error) {
	l := logic.NewHotAnchorLogic(ctx, s.svcCtx)
	return l.HotAnchor(in)
}

// cache admin
func (s *ApiproServer) RefreshCache(ctx context.Context, in *apipro.CacheRefreshReq) (*apipro.CacheRefreshResp, error) {
	l := logic.NewRefreshCacheLogic(ctx, s.svcCtx)
	return l.RefreshCache(in)
}

func (s *ApiproServer) CacheStats(ctx context.Context, in *apipro.Empty) (*apipro.CacheStatsResp, error) {
	l := logic.NewCacheStatsLogic(ctx, s.svcCtx)
	return l.CacheStats(in)
}
